version: '3.4'

services:
    adessorideshare_db:
        container_name: adessorideshare_db
        restart: always
        ports:
            - "6379:6379" #Redis officially exposing on that port

    adessorideshare.api:
        container_name: adessorideshare_api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "ConnectionStrings:Redis=adessorideshare_db:6379" #should match the container name include Redis
        depends_on:
            - adessorideshare_db
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "9000:80"